### ISSUE TITLE
tips for your killaura bot check

### ISSUE THREAD

**Issue by coolpvpv** [zLexis/LionGuard#7]
make the bot 3 blocks away behind the player so if a player was using 3.1 reach on killaura then would still hit it and legits could false it but you would have to hit at 3 blocks which is rlly hard to that exactly like that so maybe 3.1 blocks away idk btw make the bots players cause hackers could just turn off mobs and animals in there aura and make the bots wear armor and make it so other players cant see the other players bots cause then players could see them and then hit them to false the check

**Comment by zLexis** [comment]
Improved for the new version 4.1
